version: '3'
services:
  like-app:
    restart: on-failure
    build: .
    networks:
      - socialnetwork
    volumes:
      - ./:/usr/src/app
    depends_on:
      - like-mongo

  like-nginx: 
    image: nginx:latest
    container_name: nginx-like
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8083:80
    networks:
      - socialnetwork  
    depends_on:
      - like-app

  like-mongo:
    container_name: like-mongo
    image: mongo
    ports:
      - "27020:27017"
    networks:
      - socialnetwork
    volumes:
      - ./mongo/data/db:/data/db

networks:
  socialnetwork: