version: '3'
services:
  post-app:
    restart: on-failure
    build: .
    env_file:
      - .env
    networks:
      - socialnetwork
    volumes:
      - ./:/usr/src/app
    depends_on:
      - post-mongo

  post-nginx: 
    image: nginx:latest
    container_name: post-nginx
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8081:80
    networks:
      - socialnetwork  
    depends_on:
      - post-app

  post-mongo:
    container_name: post-mongo
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - socialnetwork
    volumes:
      - ./mongo/data/db:/data/db

networks:
  socialnetwork: