version: '3'
services:
  comment-app:
    restart: on-failure
    build: .
    env_file:
      - .env
    networks:
      - socialnetwork
    volumes:
      - ./:/usr/src/app
    depends_on:
      - comment-mongo

  comment-nginx: 
    image: nginx:latest
    container_name: comment-nginx
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8082:80
    networks:
      - socialnetwork  
    depends_on:
      - comment-app

  comment-mongo:
    container_name: comment-mongo
    image: mongo
    ports:
      - "27019:27017"
    networks:
      - socialnetwork
    volumes:
      - ./mongo/data/db:/data/db

networks:
  socialnetwork:
