version: '3'
services:
  gateway-app:
    restart: on-failure
    build: .
    env_file:
      - .env
    networks:
      - socialnetwork
    volumes:
      - ./:/usr/src/app

  gateway-nginx: 
    image: nginx:latest
    container_name: gateway-nginx
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8084:80
    networks:
      - socialnetwork  
    depends_on:
      - gateway-app

networks:
  socialnetwork:
