version: '3'
services:
  user-app:
    restart: on-failure
    build: .
    env_file:
      - .env
    networks:
      - socialmedia
    volumes:
      - ./:/usr/src/app
    depends_on:
      - user-mongo

  user-nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-load-balancer/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
    networks:
      - socialmedia  
    depends_on:
      - user-app

  user-mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27018:27017"
    networks:
      - socialmedia
    volumes:
      - ./mongo/data/db:/data/db

networks:
  socialmedia: